# Generated by Django 5.0.6 on 2024-06-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.TextField(default=0, max_length=15, verbose_name='شماره\u200cتلفن'),
            preserve_default=False,
        ),
    ]
