# Generated by Django 5.0.6 on 2024-06-18 21:14

import unicourse.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicourse', '0004_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[unicourse.validators.validate_phone_number]),
        ),
    ]
