# Generated by Django 5.0.6 on 2024-06-19 00:47

import django.db.models.deletion
import unicourse.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicourse', '0005_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='license',
            field=models.TextField(max_length=10, verbose_name='license code'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='national_code',
            field=models.TextField(max_length=15, validators=[unicourse.validators.validate_national_code], verbose_name='National Code'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
