# Generated by Django 5.0.6 on 2024-06-19 00:48

import unicourse.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicourse', '0006_alter_teacher_license_alter_teacher_national_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='license',
            field=models.TextField(max_length=10, verbose_name='license'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='national_code',
            field=models.CharField(max_length=15, validators=[unicourse.validators.validate_national_code], verbose_name='National Code'),
        ),
    ]
