# Generated by Django 5.0.6 on 2024-06-19 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicourse', '0007_alter_teacher_license_alter_teacher_national_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='license',
            field=models.TextField(max_length=30, verbose_name='license'),
        ),
    ]
