# Generated by Django 5.0.6 on 2024-06-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicourse', '0008_alter_teacher_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Institute Name')),
                ('address', models.TextField(max_length=200, verbose_name='Address')),
                ('license', models.TextField(max_length=30, verbose_name='License')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Is Approved')),
            ],
        ),
    ]
