# Generated by Django 5.0.6 on 2024-07-30 18:06

import django.db.models.deletion
import unicourse.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unicourse", "0011_remove_institute_name_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=30, verbose_name="اسم دوره")),
                ("price", models.IntegerField(default=0, verbose_name="هزینه دوره")),
                (
                    "prerequisite",
                    models.JSONField(
                        blank=True, default=list, verbose_name="دوره های پیشنیاز"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاریخ شروع دوره")),
                ("end_date", models.DateField(verbose_name="تاریخ پایان دوره")),
                (
                    "days_of_week",
                    models.JSONField(
                        default=list, verbose_name="روزهای برگزاری دوره در هفته"
                    ),
                ),
                (
                    "class_start_time",
                    models.TimeField(verbose_name="زمان شروع دوره در روز"),
                ),
                (
                    "class_end_time",
                    models.TimeField(verbose_name="زمان پایان دوره در روز"),
                ),
                (
                    "link_adr",
                    models.URLField(
                        default="https://nikan.iut.ac.ir/rooms/tg4-o7q-ibk-hwd/join",
                        verbose_name="لینک برگزاری دوره",
                    ),
                ),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="unicourse.institute",
                        verbose_name="آموزشگاه",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="unicourse.teacher",
                        verbose_name="استاد",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=unicourse.models.Course,
                        to="unicourse.course",
                        verbose_name="دوره",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="unicourse.student",
                        verbose_name="فراگیر",
                    ),
                ),
            ],
        ),
    ]
